# Header
menu:
  主页: /
  所有文章: /archives
  # 随笔: /tags/随笔

# SubNav
subnav:
  # github: "#"
  # zhihu: "#"
  # mail: "#"
  # qq: "#"
  # weibo: "#"
  # rss: "#"
  #douban: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

# Content
# excerpt_link: 阅读全文
excerpt_link: more
fancybox: true
mathjax: true

# 是否开启动画效果
animate: true

# 是否在新窗口打开链接
open_in_new: false

# 百度统计、谷歌统计
# baidu_tongji: true
# google_analytics: true

favicon: https://avatars.slirv.vip/alice

#你的头像url
avatar:  https://avatars.slirv.vip/alice

#是否开启分享
share: true

#是否开启多说评论，填写你在多说申请的项目名称 duoshuo: duoshuo-key
#若使用disqus，请在博客config文件中填写disqus_shortname，并关闭多说评论
# duoshuo: your duoshuo id

#是否开启云标签
tagcloud: true

#是否开启文章阅读量
leancloud_visitors:
  enable: false
  app_id: your_app_id
  app_key: your_app_key


#是否开启友情链接
#不开启——
#friends: false
#开启——
friends:
  smackdown: https://github.com/smackgg/hexo-theme-smackdown
  mailset: https://www.mailset.top/
  Souiken: https://blog.raineast.icu/
  晓雨杂记: https://lihaoyu.cn/
  方块水族箱: https://www.cube-aquarium.link/
  秉鑫: https://byteloid.one/
  japerz: https://japerz.com/
  萌ICP备20230387号: https://icp.gov.moe/?keyword=20230387
  CrashMC: https://crashmc.com/
  雨空のRainSky: https://www.zidusama.xyz/friends/
  Restent's Notebook: https://blog.gxres.net/
  XieXiLin 的小站: https://www.xiexilin.com


#是否开启“关于我”。
# 不开启——
aboutme: false
#开启——
# aboutme:

swift_search:
  enable: true
